using Pkg; Pkg.activate("."); Pkg.resolve(); Pkg.instantiate(); Pkg.update(); Pkg.precompile() 
Pkg.add("ArgParse")
using ArgParse
using YAML

function parse_commandline()
    s = ArgParseSettings()
    @add_arg_table s begin
        "--hdf5parse"
            help = "Path to the HDF5 generated by the parsing script (HiRepParsing)"
            required = true
        "--hdf5output"
            help = "Path to the output HDF5 with the meson correlators (MixedRepSinglets)"
        "--ensemble"
            help = "Name of the ensemble to be analyzed."
            required = true
        "--config_yaml"
            help = "Path to the YAML configuration file."
            required = true
    end
    return parse_args(s)
end

write_correlator   = true
paramter_path  = "input/parameters/"

args = parse_commandline()
hdf5parse = args["hdf5parse"] * "/"
hdf5out = args["hdf5output"] * "/"
ensemble = args["ensemble"]
config_yaml = args["config_yaml"]
config = YAML.load_file(config_yaml)

NsmearFUN_ini = config["ensembles"][ensemble]["rep"]["FUN"]["smear_lvl_ini"]
NsmearFUN_step = config["ensembles"][ensemble]["rep"]["FUN"]["smear_lvl_step"]
NsmearFUN_end = config["ensembles"][ensemble]["rep"]["FUN"]["smear_lvl_end"]
NsmearFUN = collect(NsmearFUN_ini:NsmearFUN_step:NsmearFUN_end)

NsmearAS_ini = config["ensembles"][ensemble]["rep"]["AS"]["smear_lvl_ini"]
NsmearAS_step = config["ensembles"][ensemble]["rep"]["AS"]["smear_lvl_step"]
NsmearAS_end = config["ensembles"][ensemble]["rep"]["AS"]["smear_lvl_end"]
NsmearAS = collect(NsmearAS_ini:NsmearAS_step:NsmearAS_end)


# In order to repsect the dataset size limit on zenodo, only_singlet
# the relevant channels (γ5, γ0γ5, γi) are written to hdf5 file sizes. 
# In order to write all channels to the hdf5 file, set the following
# variable 'write_all_channes_to_hdf5' to 'true'
write_all_channes_to_hdf5 = false

include("run_analysis.jl")  