using Pkg; Pkg.activate("."); Pkg.resolve(); Pkg.instantiate(); Pkg.update(); Pkg.precompile() 
Pkg.add("ArgParse")
using ArgParse

function parse_commandline()
    s = ArgParseSettings()
    @add_arg_table s begin
        "--hdf5parse"
            help = "Path to the HDF5 generated by the parsing script (HiRepParsing)"
            required = true
        "--hdf5output"
            help = "Path to the output HDF5 with the meson correlators (MixedRepSinglets)"
        "--ensemble"
            help = "Name of the ensemble to be analyzed."
            required = true
    end
    return parse_args(s)
end

write_correlator   = true
paramter_path  = "input/parameters/"

args = parse_commandline()
hdf5parse = args["hdf5parse"] * "/"
hdf5out = args["hdf5output"] * "/"
ensemble = args["ensemble"]

# In order to repsect the dataset size limit on zenodo, only_singlet
# the relevant channels (γ5, γ0γ5, γi) are written to hdf5 file sizes. 
# In order to write all channels to the hdf5 file, set the following
# variable 'write_all_channes_to_hdf5' to 'true'
write_all_channes_to_hdf5 = false

include("run_analysis.jl")  