using Pkg
Pkg.activate(".")
using ArgParse
using CSV
using DataFrames

function parse_commandline()
    s = ArgParseSettings()
    @add_arg_table s begin
        "--hdf5parse"
            help = "Path to the HDF5 generated by the parsing script (HiRepParsing)"
            required = true
        "--hdf5output"
            help = "Path to the output HDF5 with the meson correlators (MixedRepSinglets)"
            required = true
        "--ensemble"
            help = "Name of the ensemble to be analyzed."
            required = true
        "--meson_measurements_metadata"
            help = "Path to the metadata file containing meson measurements information."
            required = true
    end
    return parse_args(s)
end

write_correlator   = true

args = parse_commandline()
hdf5parse = args["hdf5parse"] * "/"
hdf5out = args["hdf5output"] * "/"
ensemble = args["ensemble"]

meson_measurements_metadata = args["meson_measurements_metadata"]
meson_measurements_df = CSV.read(meson_measurements_metadata, DataFrame)

ensemble_fun_rows = filter(row -> row.ensemble_name == ensemble && row.representation == "FUN", meson_measurements_df)
NsmearFUN_ini = ensemble_fun_rows[1, :wuppertal_lvl_ini]
NsmearFUN_step = ensemble_fun_rows[1, :wuppertal_lvl_step]
NsmearFUN_end = ensemble_fun_rows[1, :wuppertal_lvl_end]
NsmearFUN = collect(NsmearFUN_ini:NsmearFUN_step:NsmearFUN_end)

ensemble_as_rows = filter(row -> row.ensemble_name == ensemble && row.representation == "AS", meson_measurements_df)
NsmearAS_ini = ensemble_as_rows[1, :wuppertal_lvl_ini]
NsmearAS_step = ensemble_as_rows[1, :wuppertal_lvl_step]
NsmearAS_end = ensemble_as_rows[1, :wuppertal_lvl_end]
NsmearAS = collect(NsmearAS_ini:NsmearAS_step:NsmearAS_end)

include("run_analysis.jl")  